language: r

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
r_binary_packages:
 - testthat
